services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: taskservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations

    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_USER}:5432/${POSTGRES_DB}?sslmode=disable",
        "postgres://postgres:postgres@postgres:5432/taskservice?sslmode=disable",
        "up",
      ]

  app:
    build: .
    container_name: app
    restart: unless-stopped
    environment:
      HTTP_ADDR: :8080
      DATABASE_DSN: postgres://postgres:postgres@postgres:5432/taskservice?sslmode=disable
      GIN_MODE: release
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"

volumes:
  postgres_data:
